In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("gdp.csv")

In [3]:
df.head()

  Country Name Country Code  Year         Value
0   Arab World          ARB  1968  2.576068e+10
1   Arab World          ARB  1969  2.843420e+10
2   Arab World          ARB  1970  3.138550e+10
3   Arab World          ARB  1971  3.642691e+10
4   Arab World          ARB  1972  4.331606e+10

In [4]:
df_pr = df[df["Country Name"]=='Arab World']

In [5]:
# 1970 - 3.138
# 1969 - 2.843
# 1970 - 3.138

In [6]:
# factor by which gdp is increasing

In [7]:
round(((2.843-2.576)/2.576)*100,2)    #increasing by 10 percent

10.36

In [8]:
data = df_pr.values
gdp_change = [0]
for i in range(1,len(data)):
   gdp_change.append(round((data[i][3]-data[i-1][3])/data[i-1][3]*100,2))

In [9]:
df_pr.assign(GDP = gdp_change)

   Country Name Country Code  Year         Value    GDP
0    Arab World          ARB  1968  2.576068e+10   0.00
1    Arab World          ARB  1969  2.843420e+10  10.38
2    Arab World          ARB  1970  3.138550e+10  10.38
3    Arab World          ARB  1971  3.642691e+10  16.06
4    Arab World          ARB  1972  4.331606e+10  18.91
5    Arab World          ARB  1973  5.501839e+10  27.02
6    Arab World          ARB  1974  1.051458e+11  91.11
7    Arab World          ARB  1975  1.163370e+11  10.64
8    Arab World          ARB  1976  1.448462e+11  24.51
9    Arab World          ARB  1977  1.673083e+11  15.51
10   Arab World          ARB  1978  1.835555e+11   9.71
11   Arab World          ARB  1979  2.486462e+11  35.46
12   Arab World          ARB  1980  3.381775e+11  36.01
13   Arab World          ARB  1981  3.485928e+11   3.08
14   Arab World          ARB  1982  3.243288e+11  -6.96
15   Arab World          ARB  1983  3.039625e+11  -6.28
16   Arab World          ARB  1984  3.079408e+11   1.31
17   Arab World          ARB  1985  3.038936e+11  -1.31
18   Arab World          ARB  1986  2.890292e+11  -4.89
19   Arab World          ARB  1987  3.126817e+11   8.18
20   Arab World          ARB  1988  3.075030e+11  -1.66
21   Arab World          ARB  1989  3.223251e+11   4.82
22   Arab World          ARB  1990  4.468772e+11  38.64
23   Arab World          ARB  1991  4.397792e+11  -1.59
24   Arab World          ARB  1992  4.711635e+11   7.14
25   Arab World          ARB  1993  4.765136e+11   1.14
26   Arab World          ARB  1994  4.875269e+11   2.31
27   Arab World          ARB  1995  5.237599e+11   7.43
28   Arab World          ARB  1996  5.782313e+11  10.40
29   Arab World          ARB  1997  6.132795e+11   6.06
30   Arab World          ARB  1998  5.915256e+11  -3.55
31   Arab World          ARB  1999  6.438897e+11   8.85
32   Arab World          ARB  2000  7.350251e+11  14.15
33   Arab World          ARB  2001  7.232828e+11  -1.60
34   Arab World          ARB  2002  7.290517e+11   0.80
35   Arab World          ARB  2003  8.231105e+11  12.90
36   Arab World          ARB  2004  9.638623e+11  17.10
37   Arab World          ARB  2005  1.184662e+12  22.91
38   Arab World          ARB  2006  1.404114e+12  18.52
39   Arab World          ARB  2007  1.637573e+12  16.63
40   Arab World          ARB  2008  2.078116e+12  26.90
41   Arab World          ARB  2009  1.795820e+12 -13.58
42   Arab World          ARB  2010  2.109646e+12  17.48
43   Arab World          ARB  2011  2.501554e+12  18.58
44   Arab World          ARB  2012  2.741239e+12   9.58
45   Arab World          ARB  2013  2.839627e+12   3.59
46   Arab World          ARB  2014  2.906616e+12   2.36
47   Arab World          ARB  2015  2.563302e+12 -11.81
48   Arab World          ARB  2016  2.504703e+12  -2.29